"""Initial migration

Revision ID: 6209fc0fa4e1
Revises: 
Create Date: 2025-07-29 23:31:27.360274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6209fc0fa4e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('trips', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('discription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'description')
    # ### end Alembic commands ###
